// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTlOl9cLfrvWlRK0Kd6UhzmnbGYvEqmgc',
    appId: '1:1047152421133:web:661019c6eace5600566844',
    messagingSenderId: '1047152421133',
    projectId: 'rentcar-593a1',
    authDomain: 'rentcar-593a1.firebaseapp.com',
    databaseURL: 'https://rentcar-593a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rentcar-593a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0qBcyJUhCJngCzDpNI9xlH3dM1gp_-Hw',
    appId: '1:1047152421133:android:b47d2729b502576e566844',
    messagingSenderId: '1047152421133',
    projectId: 'rentcar-593a1',
    databaseURL: 'https://rentcar-593a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rentcar-593a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnHHZnuKY_K5fgm6J8Stafb1Ok9L6PR2I',
    appId: '1:1047152421133:ios:0e76d581d894db35566844',
    messagingSenderId: '1047152421133',
    projectId: 'rentcar-593a1',
    databaseURL: 'https://rentcar-593a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rentcar-593a1.appspot.com',
    iosBundleId: 'com.example.rentCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnHHZnuKY_K5fgm6J8Stafb1Ok9L6PR2I',
    appId: '1:1047152421133:ios:0e76d581d894db35566844',
    messagingSenderId: '1047152421133',
    projectId: 'rentcar-593a1',
    databaseURL: 'https://rentcar-593a1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rentcar-593a1.appspot.com',
    iosBundleId: 'com.example.rentCar',
  );
}
